ILSCore/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ILS.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using ILS.Services.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Data;

namespace ILS.Controllers
{
    public class PartsController : Controller
    {
        private readonly ILogger<PartsController> _logger;
        private readonly IPartsService _partService;
        private IWebHostEnvironment _hostingEnvironment;
        public PartsController(IWebHostEnvironment environment, ILogger<PartsController> logger, IPartsService partService)
        {
            _hostingEnvironment = environment;
            _partService = partService;
            _logger = logger;
        }

        public ActionResult Index()
        {
            return View("PartsGrid", new PartsViewModel());
        }

        [HttpGet]
        public JsonResult GetPartsList()
        {
            var list = _partService.GetPartsList().ToPartsModelList();
            var result = Json(list);

            return result;
        }


        public ActionResult AddParts()
        {
            ViewBag.PageMode = "Add";
            return View(LoadData());
        }

        [HttpPost]
        public ActionResult AddParts(AddPartViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PictureFileName = $"{DateTime.Now.ToString("yyyymmddhhmiss")}{ model.PictureInfo.FileName}";

                    _partService.AddParts(model);

                    var folderPath = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads");
                    if (model.PictureInfo.Length > 0)
                    {
                        var filePath = Path.Combine(folderPath, model.PictureFileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            model.PictureInfo.CopyToAsync(fileStream);
                        }
                    }

                    TempData.Put("Message", new NotificationViewModel() { Message = $"Part '{model.PartName}' added succesfully.", MessageType = NotificationType.success });
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.PageMode = "Add";

                    ModelState.AddModelError("", "There are errors, please  correct them to continue!");
                    model = LoadData();
                    return View("AddParts", model);
                }
            }
            catch (Exception ex)
            {
                TempData.Put("Message", new NotificationViewModel() { Message = ex.ToString(), MessageType = NotificationType.error });
                return View("AddParts", model);
            }
        }
        public AddPartViewModel LoadData()
        {
            AddPartViewModel vm = new AddPartViewModel();
            vm.PartCategoryItems = _partService.GetPartsCategory().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.CategoryId,
                Text = c.Description
            });
            vm.PartTypeItems = _partService.GetPartType().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.PartType,
                Text = c.PartTypeDescription
            });
            vm.CurrencyItems = _partService.GetCurrency().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.UnitItems = _partService.GetUnitItems().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });
            vm.MaterialCategoryItems = _partService.GetMaterialcCategoryItems().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.APItems = _partService.GetAPItemsList().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.ACItems = _partService.GetACItemsList().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.ASCItems = _partService.GetASCItemsList().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.ShelfLifeItems = _partService.GetShelfLifeItems().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.LeadTimeItems = _partService.GetLeadTimeItems().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.OSIItems = _partService.GetOSIItems().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.UnitCubeItems = _partService.GetUnitCubeItems().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });

            vm.SecurityItems = _partService.GetSecurityItems().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.ID,
                Text = c.Description
            });


            return vm;
        }

        public IActionResult Edit(string id)
        {
            var partDetails = _partService.GetPartById(Convert.ToInt32(id));
            if (partDetails != null)
            {
                var model = LoadData();

                var partViewModel = partDetails.ToViewModel();
                partViewModel.PartCategoryItems = model.PartCategoryItems;
                partViewModel.PartTypeItems = model.PartTypeItems;
                partViewModel.CurrencyItems = model.CurrencyItems;
                partViewModel.UnitItems = model.UnitItems;
                partViewModel.MaterialCategoryItems = model.MaterialCategoryItems;
                partViewModel.APItems = model.APItems;
                partViewModel.ACItems = model.ACItems;
                partViewModel.ASCItems = model.ASCItems;
                partViewModel.ShelfLifeItems = model.ShelfLifeItems;
                partViewModel.LeadTimeItems = model.LeadTimeItems;
                partViewModel.OSIItems = model.OSIItems;
                partViewModel.UnitCubeItems = model.UnitCubeItems;
                partViewModel.SecurityItems = model.SecurityItems;


                var folderPath = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads");

                partViewModel.PictureFileName = $"\\Uploads\\{partViewModel.PictureFileName}";

                var cageInfo = _partService.GetCageInfo(Convert.ToInt32(partViewModel.ManufacturerId)).FirstOrDefault();

                if (cageInfo != null)
                {
                    partViewModel.ManufacturerName = cageInfo.ManufacturerName;
                    partViewModel.CageCode = model.GroupModelId;
                }

                return View("AddParts", partViewModel);
            }
            else
            {
                TempData.Put("Message", new NotificationViewModel() { Message = "Part not found.", MessageType = NotificationType.error });
            }
            return View();
        }


        #region Helper Functions
        [HttpGet]
        public ActionResult GetPartType()
        {

            var list = _partService.GetPartType().ToViewModel();

            return Json(list);
        }

        [HttpPost]
        public JsonResult GetPartCategory()
        {

            return Json(_partService.GetPartType().ToViewModel().Select(c => new SelectListItem
            {
                Value = c.PartType,
                Text = c.PartTypeDescription
            }));

        }

        [HttpGet]
        public JsonResult GetGroupInfo()
        {
            return Json(new { data = _partService.GetGroupInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetCageInfo()
        {
            return Json(new { data = _partService.GetCageInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetVendorInfo()
        {
            return Json(new { data = _partService.GetCageInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetMECInfo()
        {
            return Json(new { data = _partService.GetMECInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetANCInfo()
        {
            return Json(new { data = _partService.GetANCInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetAPPInfo()
        {
            return Json(new { data = _partService.GetAPPInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetCustodyInfo()
        {
            return Json(new { data = _partService.GetCustodyInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetSMCInfo()
        {
            return Json(new { data = _partService.GetSMCInfo().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetDerivativeInfo()
        {
            return Json(new { data = _partService.GetDerivativeItems().ToViewModel() });
        }

        [HttpGet]
        public JsonResult GetSMICInfo()
        {
            return Json(new { data = _partService.GetSMICItems().ToViewModel() });
        }

        [HttpGet]

ILSCore/ViewComponents/NotificationViewComponent.cs
using ILS.Services.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ILS_Core.ViewComponents
{
    public class NotificationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(NotificationViewModel model)
        {
            return View(model);
        }
    }
}

ILSCore/Views/Parts/Index.cshtml
@Html.Partial("RolesGrid")

ILSCore/Views/Parts/PartsGrid.cshtml
@using ILS.Services.ViewModels 
<script src="@Url.Content("~/assets/global/plugins/jquery.min.js")"></script>
<script src="@Url.Content("~/assets/pages/scripts/table-datatables-responsive.min.js")"></script>
<script src="@Url.Content("~/assets/pages/scripts/ag-grid-enterprise.min.noStyle.js")"></script>

<script src="@Url.Content("~/assets/global/scripts/datatable.js")"></script>
<script src="@Url.Content("~/assets/global/plugins/datatables/datatables.min.js")"></script>
<script src="@Url.Content("~/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")"></script>

<script>
    $(document).ready(function () {

        toastr.options = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-top-center",
            "onclick": null,
            "showDuration": "1000",
            "hideDuration": "1000",
            "timeOut": "1000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        debugger;
        @*if (@TempData["Message"]!= null) {
            toastr.error((@TempData["Message"]), "Success");
       }*@
    });
</script>
<br />
<div class="portlet red-sunglo box">

    <div class="portlet-title">
        <div class="caption">
            <span class="fa fa-cogs"> Parts</span>
        </div>

        <div class="actions">
            <a href="@Url.Action("AddParts", "Parts")" class="btn btn-default btn-sm">
                <i class="fa fa-plus"></i>
                Add part
            </a>
        </div>

    </div>

    <div class="portlet-body">

        <div class="input-icon right">
            <i class="fa fa-search fa-spin font-blue"></i>
            <input type="text" class="form-control" id="filter-text-box" placeholder="Filter data...." oninput="onFilterTextBoxChanged()">
        </div>

        <br />
        <div id="myGrid" style="height: 420px; " class="ag-theme-material"></div>
    </div>

</div>

@if (TempData["Message"] != null)
{
@await Component.InvokeAsync("Notification", TempData.Get<NotificationViewModel>("Message"))
}

<script type="text/javascript" charset="utf-8">


    var detailsRenderer = function (params) {
        var eDiv = document.createElement('div');

        eDiv.className = "btn-group";

        eDiv.innerHTML = '<a href="javascript:;" class="btn-edit btn btn-xs blue"> Edit<i class="fa fa-edit" ></i></a><a href="javascript:;" class="btn-view btn btn-xs green"> View<i class="fa fa-search" ></i></a> <a href="javascript:;" class="btn-del btn btn-xs red"> Delete<i class="fa fa-times" ></i></a>';

        var eButtonEdit = eDiv.querySelectorAll('.btn-edit')[0];
        var eButtonView = eDiv.querySelectorAll('.btn-view')[0];
        var eButtonDel = eDiv.querySelectorAll('.btn-del')[0];

       const partId = params.node.data["PartId"];

        eButtonEdit.addEventListener('click', function () {
               window.location.href = '@Url.Action("Edit", "Parts")?id=' + partId;
        });

        eButtonView.addEventListener('click', function () {
               window.location.href = '@Url.Action("Edit", "Parts")?id=' + partId;
        });

        eButtonDel.addEventListener('click', function () {
                if (confirm("Are you sure you want to delete????"))
                {
                  window.location.href = '@Url.Action("Edit", "Parts")?id=' + partId;
                }
            });

        return eDiv;
    }



    // specify the columns
    var columnDefs = [
        {
            field: "PartId",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
            enableRowGroup: true,
            checkboxSelection: function (params) {
                // we put checkbox on the name if we are not doing grouping
                return params.columnApi.getRowGroupColumns().length === 0;
            }
            //,
            //headerCheckboxSelection: function (params) {
            //    // we put checkbox on the name if we are not doing grouping
            //    return params.columnApi.getRowGroupColumns().length === 0;
            //}
        },
        {
            headerName: "Part No",
            field: "PartNo",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
            enableRowGroup: true
        },
        {
            headerName: "Part Name",
            field: "PartName",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
            enableRowGroup: true
        },
        {
            headerName: "Actions",
            field: null,
            cellRenderer: detailsRenderer,

        }
    ];

    function onFilterTextBoxChanged() {
        gridOptions.api.setQuickFilter(document.getElementById('filter-text-box').value);
    }

    var autoGroupColumnDef = {
        headerName: 'Part Id',
        minWidth: 170,
        field: 'PartId',
        valueGetter: function (params) {
            if (params.node.group) {
                return params.node.key;
            } else {
                return params.data[params.colDef.field];
            }
        },
        headerCheckboxSelection: true,
        // headerCheckboxSelectionFilteredOnly: true,
        //cellRenderer: 'agGroupCellRenderer',
        cellRendererParams: {
            checkbox: true,
        }
    };


    //var gridOptions = {
    //    defaultColDef: {
    //        editable: true,
    //        enableRowGroup: true,
    //        enablePivot: true,
    //        enableValue: true,
    //        sortable: true,
    //        resizable: true,
    //        filter: true,
    //        flex: 1,
    //        minWidth: 100,
    //    },

    //    //suppressRowClickSelection: true,
    //    //groupSelectsChildren: true,
    //    //rowSelection: 'multiple',
    //    //rowGroupPanelShow: 'always',
    //    //pivotPanelShow: 'always',
    //    //enableRangeSelection: true,

    //    columnDefs: columnDefs,
    //    paginationAutoPageSize: true,
    //    pagination: true,
    //    autoGroupColumnDef: autoGroupColumnDef,

    //      // Header grouping
    //    suppressDragLeaveHidesColumns: true,
    //    suppressMakeColumnVisibleAfterUnGroup: true,
    //    rowGroupPanelShow: 'always',
    //    //
    //};


    var gridOptions = {
        defaultColDef: {
            flex: 1,
            sortable: true,
            filter: true,
            resizable: true
        },

        columnDefs: columnDefs,
        rowData: null,
        //floatingFilter: true,

        onColumnResized: function (params) { },

        alwaysShowVerticalScroll: true,

        // pagination
        paginationPageSize: 10,
        pagination: true,
        //
        // Header grouping
        suppressDragLeaveHidesColumns: true,
        suppressMakeColumnVisibleAfterUnGroup: true,
        rowGroupPanelShow: 'always',
        //

    };

    //var allColumnsIds = [];
    //gridOptions.columnApi.getAllColumns().forEach(function (column) {
    //    allColumnsIds.push(column.colId);
    //});
    //gridOptions.columnApi.autoSizeColumns(allColumnsIds, false);

    // lookup the container we want the Grid to use
    var eGridDiv = document.querySelector('#myGrid');


    // create the grid passing in the div to use together with the columns & data we want to use
    new agGrid.Grid(eGridDiv, gridOptions);


    agGrid.simpleHttpRequest({ url: "http://localhost/ILS/Parts/GetPartsList" }).then(function (data) {
        gridOptions.api.setRowData(data);
    });

    function getSelectedRows() {
        const selectedNodes = gridOptions.api.getSelectedNodes()
        const selectedData = selectedNodes.map(function (node) { return node.data })
        const selectedDataStringPresentation = selectedData.map(function (node) { return node.make + ' ' + node.model }).join(', ')
        alert('Selected nodes: ' + selectedDataStringPresentation);
    }
</script>

ILSCore/Views/Parts/PartsList.cshtml
@using ILS.Services.ViewModels

<script src="@Url.Content("~/assets/global/plugins/jquery.min.js")"></script>
<script src="@Url.Content("~/assets/pages/scripts/table-datatables-responsive.min.js")"></script>
<script src="@Url.Content("~/assets/pages/scripts/ag-grid-enterprise.min.noStyle.js")"></script>

<script src="@Url.Content("~/assets/global/scripts/datatable.js")"></script>
<script src="@Url.Content("~/assets/global/plugins/datatables/datatables.min.js")"></script>
<script src="@Url.Content("~/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")"></script>

<script>
    $(document).ready(function () {

        toastr.options = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-top-center",
            "onclick": null,
            "showDuration": "1000",
            "hideDuration": "1000",
            "timeOut": "1000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
     
    });
</script>
 
<div class="portlet red-sunglo box">

    <div class="portlet-title">
        <div class="caption">
            @if (ViewData["Mode"]?.ToString() == "Equipment")
            {
                <span class="fa fa-cogs"> Equipment Configuration</span>
            }
            else
            {
                <span class="fa fa-cogs"> Parts List</span>
            }
        </div>
    </div>

    <div class="portlet-body">

        
        <br />
        <div id="myGrid" style="height: 420px; " class="ag-theme-material"></div>
    </div>

</div>

@if (TempData["Message"] != null)
{
    @await Component.InvokeAsync("Notification", TempData.Get<NotificationViewModel>("Message"))
}

<script type="text/javascript" charset="utf-8">


    var detailsRenderer = function (params) {
        var eDiv = document.createElement('div');

        eDiv.className = "btn-group";

        eDiv.innerHTML = '<a href="javascript:;" class="btn-edit btn btn-xs blue"> Edit<i class="fa fa-edit" ></i></a><a href="javascript:;" class="btn-view btn btn-xs green"> View<i class="fa fa-search" ></i></a> <a href="javascript:;" class="btn-del btn btn-xs red"> Delete<i class="fa fa-times" ></i></a><a href="javascript:;" class="btn-config btn btn-xs grey"> Config<i class="fa fa-link" ></i></a>';

        var eButtonEdit = eDiv.querySelectorAll('.btn-edit')[0];
        var eButtonView = eDiv.querySelectorAll('.btn-view')[0];
        var eButtonDel = eDiv.querySelectorAll('.btn-del')[0];
        var eButtonConfig = eDiv.querySelectorAll('.btn-config')[0];

       const partId = params.node.data["partId"];

        eButtonEdit.addEventListener('click', function () {
               window.location.href = '@Url.Action("EditChildPart", "Parts")?id=' + partId;
        });

        eButtonView.addEventListener('click', function () {
               window.location.href = '@Url.Action("ViewChildPart", "Parts")?id=' + partId;
        });

        eButtonDel.addEventListener('click', function () {
                if (confirm("Are you sure you want to delete????"))
                {
                  window.location.href = '@Url.Action("DeleteChildPart", "Parts")?id=' + partId;
                }
        });

        eButtonConfig.addEventListener('click', function () {
               window.location.href = '@Url.Action("TreeView", "Parts")?id=' + partId;
        });

        return eDiv;
    }

    // specify the columns
    var columnDefs = [
        {
            field: "partId",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
            checkboxSelection: function (params) {
                // we put checkbox on the name if we are not doing grouping
                return params.columnApi.getRowGroupColumns().length === 0;
            }
        },
        {
            headerName: "Part No",
            field: "partNumber",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
        },
        {
            headerName: "Part Name",
            field: "partName",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
        },
        {
            headerName: "Manufacturer Name",
            field: "manufacturerName",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
        },
        {
            headerName: "Description",
            field: "description",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
        },
        {
            headerName: "Quantity",
            field: "quantity",
            filter: 'agTextColumnFilter',
            filterParams: {
                filterOptions: ['contains', 'notContains'],
                debounceMs: 0,
                caseSensitive: true,
                suppressAndOrCondition: true
            },
        },
        {
            headerName: "Actions",
            minWidth: 325,
            field: null,
            cellRenderer: detailsRenderer,
            suppressSizeToFit: true,
        }
    ];

    function onFilterTextBoxChanged() {
        gridOptions.api.setQuickFilter(document.getElementById('filter-text-box').value);
    }

    var autoGroupColumnDef = {
        headerName: 'Part Id',

        field: 'partId',
        valueGetter: function (params) {
            if (params.node.group) {
                return params.node.key;
            } else {
                return params.data[params.colDef.field];
            }
        },
        headerCheckboxSelection: true,
        cellRendererParams: {
            checkbox: true,
        }
    };

    var gridOptions = {
        defaultColDef: {
            flex: 1,
            sortable: true,
            filter: true,
            resizable: true
        },

        columnDefs: columnDefs,
        rowData: null,
        //floatingFilter: true,

        onColumnResized: function (params) { },

        alwaysShowVerticalScroll: true,

        // pagination
        paginationPageSize: 10,
        pagination: true,
        //
    };

    // lookup the container we want the Grid to use
    var eGridDiv = document.querySelector('#myGrid');


    // create the grid passing in the div to use together with the columns & data we want to use
    new agGrid.Grid(eGridDiv, gridOptions);

    var pageMode = '@ViewData["Mode"]';
    agGrid.simpleHttpRequest({ url: "https://localhost:5001/Parts/GetPartsData?filter=" + pageMode }).then(function (data) {
        gridOptions.api.setRowData(data);
    });

    function getSelectedRows() {
        const selectedNodes = gridOptions.api.getSelectedNodes()
        const selectedData = selectedNodes.map(function (node) { return node.data })
        const selectedDataStringPresentation = selectedData.map(function (node) { return node.make + ' ' + node.model }).join(', ')
        alert('Selected nodes: ' + selectedDataStringPresentation);
    }
</script>

ILSCore/Views/Parts/SiteConfigIndex.cshtml
@using ILS
@model SiteConfigSearchViewModel

<script src="@Url.Content("~/assets/global/plugins/jquery.min.js")"></script>

<script src="@Url.Content("~/assets/global/plugins/jquery-ui/jquery-ui.min.js")"></script>
<script src="@Url.Content("~/assets/global/scripts/app.min.js")"></script>



<div class="portlet portlet-sortable light bordered">
    <div class="portlet-title ui-sortable-handle">
        <div class="caption font-green">
            <i class="icon-settings font-green"></i>
            <span class="caption-subject bold"> Site Configuration</span>
        </div>

        <div class="tools">
            <a href="" class="collapse"> </a>
            <a href="" class="fullscreen"> </a>
        </div>
    </div>

    <div class="portlet-body form">
        <div class="row">
            <div class="col-md-5">
                <div class="form-group form-md-line-input form-md-floating-label">
                    @Html.DropDownListFor(x => x.SiteId, Model.ConfiguredSitesList, new { @class = "form-control", id = "ddSitesList" })
                    <label id="lblSiteId" for="form_control_1">Select Site</label>
                    <span class="help-block">@Html.ValidationMessageFor(x => x.SiteId)</span>
                </div>
            </div>

            <div class="col-md-7">
                <div class="form-group form-md-line-input form-md-floating-label">
                    <div class="input-group">
                        <div class="input-group-control">
                            @Html.DropDownListFor(x => x.SchemeId, Model.Schemes, new { @class = "form-control", id = "ddSchemesList" })
                            <label id="lblSchemeId" for="form_control_1">Select Scheme</label>
                            <span class="help-block">@Html.ValidationMessageFor(x => x.SchemeId)</span>
                        </div>
                        <span class="input-group-btn btn-left">
                            <button id="btnViewConfiguration" class="btn green btn-large" type="button">
                                View
                                <i class="fa fa-plus"></i>
                            </button>
                        </span>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>


<script>
    //$(document).ready(function () {
    //    var ddSite = $("#ddSite");
    //    ddSite.empty().append('<option selected="selected" value="0" disabled = "disabled">Loading.....</option>');
    //    $.ajax({
    //        type: "POST",
    //        url: "/Parts/LoadConfiguredSites",
    //        data: '{}',
    //        contentType: "application/json; charset=utf-8",
    //        dataType: "json",
    //        success: function (response) {
    //            ddSite.empty().append('<option selected="selected" value="0">Please select</option>');
    //            $.each(response, function () {
    //                ddSite.append($("<option></option>").val(this['Value']).html(this['Text']));
    //            });
    //        },
    //        failure: function (response) {
    //            alert(response.responseText);
    //        },
    //        error: function (response) {
    //            alert(response.responseText);
    //        }
    //    });
    //});


    $(document).ready(function () {
        $.ajax({
            url: "/Parts/LoadConfiguredSites",
            type: "POST",
            contentType: "application/json; charset=utf-8",
            datatype: "json",
            success: function (result) {
                $(result).each(function () {
                    $("#FromJson").append($("<option></option>").val(this.SiteNo).html(this.SiteName));
                });
            },
            error: function (data) { }
        });
    });
</script>